services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ssms
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
